services:
  mysql:
    image: mysql
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isucon2021_prior
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  webapp:
    build: golang
    network_mode: host
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf:ro
