name: Main

on:
  push:
    branches:
      - 'ghaction'

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - name: Install alp
        run: |
          curl -sSLO "https://github.com/tkuchiki/alp/releases/download/v1.0.8/alp_linux_amd64.zip"
          unzip "alp_linux_amd64.zip"
        working-directory: ./webapp

      - name: Build benchmarker
        run: make build
        working-directory: ./benchmarker

      - name: Copy public
        run: |
          unlink golang/public
          cp -r frontend/dist golang/public
        working-directory: ./webapp
      - name: Build Docker images
        run: docker-compose build
        working-directory: ./webapp

      - name: Start webapp
        run: docker-compose up -d
        working-directory: ./webapp
      - name: Wait for ready
        run: sleep 5

      - name: Run benchmark
        run: |
          ./bin/benchmarker -target "127.0.0.1:80" -exit-status
        working-directory: ./benchmarker

      - run: docker-compose exec -T nginx cat /var/log/nginx/access2.log | ./alp json --reverse --output=count,2xx,3xx,4xx,5xx,method,uri,min,p50,p99,max --matching-groups=/api/schedules/[0-9A-Z]{26}
        working-directory: ./webapp
